/*
# Create message_events table for admin analytics

1. Purpose
   - Records every AI message generated by any user, so the admin panel can show
     usage metrics: total messages, messages per day/hour, average per user, peak traffic.
   - Data is associated with the authenticated user who triggered the message.

2. New Tables
   - `message_events`
     - `id` (uuid, primary key)
     - `user_id` (uuid, not null, defaults to auth.uid(), references auth.users)
     - `feature` (text, not null) — which feature produced the message (e.g. 'analysis', 'improve', 'profile', 'compliments')
     - `provider` (text, nullable) — which AI provider/key handled the request (e.g. 'groq-3')
     - `created_at` (timestamptz, default now())

3. Indexes
   - `idx_message_events_user_id` on user_id
   - `idx_message_events_created_at` on created_at (for time-based queries)

4. Security (RLS)
   - Enable RLS on message_events.
   - SELECT: only the admin email (traquinouriel@gmail.com) can read ALL rows; every other
     authenticated user can read only their own rows (so the app can show personal history).
   - INSERT: any authenticated user can insert their own row (user_id defaults to auth.uid()).
   - No UPDATE or DELETE policies — events are append-only.

5. Important Notes
   - The admin check uses auth.jwt() -> raw_app_meta_data for email. If the email is stored in
     raw_user_meta_data instead, the policy falls back to checking the profiles table.
   - This table is append-only: no update/delete policies are created.
*/

CREATE TABLE IF NOT EXISTS message_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  feature text NOT NULL,
  provider text,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_message_events_user_id ON message_events(user_id);
CREATE INDEX IF NOT EXISTS idx_message_events_created_at ON message_events(created_at);

ALTER TABLE message_events ENABLE ROW LEVEL SECURITY;

-- Admin can read all rows; non-admin users read only their own
DROP POLICY IF EXISTS "select_message_events" ON message_events;
CREATE POLICY "select_message_events"
ON message_events FOR SELECT
TO authenticated
USING (
  user_id = auth.uid()
  OR EXISTS (
    SELECT 1 FROM profiles p
    WHERE p.id = auth.uid()
      AND lower(p.email) = 'traquinouriel@gmail.com'
  )
);

-- Any authenticated user can insert their own events
DROP POLICY IF EXISTS "insert_own_message_events" ON message_events;
CREATE POLICY "insert_own_message_events"
ON message_events FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);
